name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sbacr02.azurecr.io/sidapp01:latest
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: sbacr02
        # Container registry password
        password: lZWpE79iPIJA8WHjvYoW7QqC0aMqMC/r
        # Container registry server url
        login-server: sbacr02.azurecr.io
        
    - name: Push Image  
      run: docker push sbacr02.azurecr.io/sidapp01:latest
